export default [
    'Aberdeen',
    'County Armagh',
    'Gwynedd',
    'Somerset',
    'County Antrim',
    'West Midlands',
    'West Yorkshire',
    'East Sussex',
    'Bristol',
    'Cambridgeshire',
    'Kent',
    'Glamorgan',
    'Cumbria',
    'Essex',
    'Cheshire',
    'West Sussex',
    'West Midlands',
    'Derbyshire',
    'Dundee',
    'Durham',
    'Edinburgh',
    'Cambridgeshire',
    'Devon',
    'Glasgow',
    'Gloucestershire',
    'Herefordshire',
    'Highland',
    'East Riding of Yorkshire',
    'Lancashire',
    'West Yorkshire',
    'Leicestershire',
    'Staffordshire',
    'Lincolnshire',
    'County Antrim',
    'Merseyside',
    'London',
    'County Londonderry',
    'Greater Manchester',
    'Tyne and Wear',
    'Newport City',
    'County Down',
    'Norfolk',
    'Nottinghamshire',
    'Oxfordshire',
    'Perth and Kinross',
    'Cambridgeshire',
    'Devon',
    'Hampshire',
    'Lancashire',
    'North Yorkshire',
    'Greater Manchester',
    'Wiltshire',
    'South Yorkshire',
    'Hampshire',
    'Hertfordshire',
    'Denbighshire',
    'Pembrokeshire',
    'Stirlingshire',
    'Staffordshire',
    'Tyne and Wear',
    'Swansea',
    'Cornwall',
    'West Yorkshire',
    'Somerset',
    'London',
    'Hampshire',
    'West Midlands',
    'Worcestershire',
    'North Yorkshire'
]