name: Deploy API to Production

on:
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    environment: production

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

  deploy:
    if: github.ref == 'refs/heads/main'

    uses: ./.github/workflows/deploy-api-on-call.yml
    with:
      ENVIRONMENT: prod
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EBS_APP_NAME: ${{ secrets.EBS_APP_NAME }}
      EBS_ENV_NAME: ${{ secrets.EBS_ENV_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      APP_KEY: ${{ secrets.APP_KEY }}
      RDS_HOST: ${{ secrets.RDS_HOST }}
      RDS_PSWD: ${{ secrets.RDS_PSWD }}
      S3_PUBLIC_BUCKET: ${{ secrets.S3_PUBLIC_BUCKET }}
      S3_PUBLIC_BUCKET_URL: ${{ secrets.S3_PUBLIC_BUCKET_URL }}
      S3_PRIVATE_BUCKET: ${{ secrets.S3_PRIVATE_BUCKET }}
      S3_PRIVATE_BUCKET_URL: ${{ secrets.S3_PRIVATE_BUCKET_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_RECAPTCHA_SECRET_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SECRET_KEY }}
